version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    volumes:
      - ./data/wordpress:/var/www/html
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    networks:
      - lol
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - lol
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
    volumes:
      - ./data/wordpress:/var/www/wordpress
    networks:
      - lol

networks:
  lol:
    driver: bridge
      